"""task table

Revision ID: 0bd475a78719
Revises: a865c6ec7761
Create Date: 2019-12-02 23:17:47.377372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd475a78719'
down_revision = 'a865c6ec7761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=128), nullable=False),
    sa.Column('task_due', sa.Text(), nullable=False),
    sa.Column('task_remind', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.alter_column('user', 'user_email',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
    op.drop_index('ix_user_user_email', table_name='user')
    op.create_unique_constraint(None, 'user', ['user_email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_user_email', 'user', ['user_email'], unique=1)
    op.alter_column('user', 'user_email',
               existing_type=sa.VARCHAR(length=320),
               nullable=True)
    op.drop_table('task')
    # ### end Alembic commands ###
