"""removed task  table

Revision ID: 9a4e904f7c0d
Revises: 0bd475a78719
Create Date: 2019-12-03 13:56:49.558465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4e904f7c0d'
down_revision = '0bd475a78719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_sent', sa.Integer(), nullable=True))
    op.alter_column('task', 'task_due',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('task', 'task_remind',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_task_task_due'), 'task', ['task_due'], unique=False)
    op.create_index(op.f('ix_task_task_name'), 'task', ['task_name'], unique=False)
    op.create_index(op.f('ix_task_task_remind'), 'task', ['task_remind'], unique=False)
    op.create_index(op.f('ix_task_task_sent'), 'task', ['task_sent'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_task_sent'), table_name='task')
    op.drop_index(op.f('ix_task_task_remind'), table_name='task')
    op.drop_index(op.f('ix_task_task_name'), table_name='task')
    op.drop_index(op.f('ix_task_task_due'), table_name='task')
    op.alter_column('task', 'task_remind',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('task', 'task_due',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('task', 'task_sent')
    # ### end Alembic commands ###
